### ISSUE TITLE
hook runs before tree is copied to working directory

### ISSUE THREAD

**Issue by cromega** [uber/astro#63]
I have a hook that runs a script that calls the aws cli for a session with an MFA code. The most straightforward way to configure the mfa device would be by dropping the aws username into a file, let's call it `.aws_username`. However, On executing `astro plan` I get an error, because `.aws_username` is not found. Found out the reason is that when the hook gets executed the working directory is already created under `.astro` but it's empty.

I can workaround the problem but I'm wondering if it made sense to run hooks after the working directory is populated.

**Comment by dansimau** [comment]
Can you paste your config?

The startup hook gets executed once in the beginning before anything happens. But the prerun hooks modules should happen just after the tree is copied for that module:
https://github.com/uber/astro/blob/a16ed4ddcc66eeeeea8b9db5a26ef4a8412e3cec/astro/sessions.go#L273

The other thing you could do is have your MFA tool recursively look for your `.aws_username` configuration in parent directories, similar to how git looks for a .git dir. This is what we do with our [our own MFA CLI](https://github.com/uber/assume-role-cli). Then it doesn't matter which working dir you are in your tree, as long as your config is in your project root.

**Comment by cromega** [comment]
The relevant bit of the configuration is:

```
hooks:
  startup:
    - command: "./get_session.sh"
      set_env: true
```

in my script I have:

```
echo $BASH_SOURCE > /tmp/hook.log
echo $PWD >> /tmp/hook.log
find . >> /tmp/hook.log
cat .aws_username
```

and as I said, the output of `astro plan --trace` is:

```
[TRACE] 2020/05/14 22:12:36 astro: running hook: /home/cromega/code/platform/get_session.sh
cat: .aws_username: No such file or directory
error running Startup hook: exit status 1
```

the contents of the tmp file:

```
/home/cromega/code/platform/get_session.sh
/home/cromega/code/platform/.astro/01E8AD81520EE73AM4PH7A8NAC
.
```

So you were right saying the hook runs before the script is copied, however, the working directory is set to the target folder but it's stil empty.

**Comment by dansimau** [comment]
Is your terraform code dir at `/home/cromega/code`, or is it outside this tree?

If it's inside the same tree, you can just look two directories up in the tree (e.g. `../../`).

If it's outside, you could run the hook before each module is run, which will happen after it copies the terraform root. Defining a hook in a module looks like:

```
modules:
  - name: app
    path: core/app
        pre_module_run:
            - command: "./your_command_here"
    [...]
```

Hope this helps.

**Comment by cromega** [comment]
Thanks for the suggestion! There are ways to work around the problem, but I still think there is a certain amount of surprise-factor involved :)

**Comment by dansimau** [comment]
What if we change the working directory of the startup script to be the terraform root? That seems to make sense to me. It is a breaking change though.

**Comment by cromega** [comment]
Terraform root meaning the folder where astro is executed in? (In my case it's the repo root).

**Comment by dansimau** [comment]
Terraform code root meaning the value of `terraform_code_root` in the astro.yaml config (https://github.com/uber/astro/blob/master/astro/conf/astro.go#L46). It defaults to the location of `astro.yaml`.

(The `terraform_code_root` is also what is copied into the session/module directory before a module is run.)

**Comment by cromega** [comment]
`Defaults to the same directory as the config file.`. Right. So, yes, I think that's a reasonable change. At least according to the way I expected the tool to work.
