### ISSUE TITLE
Add subcommand to print output

### ISSUE THREAD

**Issue by cromega** [uber/astro#64]
Right now there is no way to get the output of root terraform modules that doesn't involve running terraform manually. It would be nice if there was an `astro output` command, maybe even an optional flag for `apply` to print the output of each module when they finished.

```
astro output --config x.yaml --modules y,z
#
astro apply --output
```

**Comment by dansimau** [comment]
You can view the logs of all previous commands that were run by manually looking in the .astro directory:

```
.astro/<sessionID>/<module>/logs/
```

There should be a log file in there corresponding to the command run (e.g. `plan.log` or `apply.log`).

However, I agree it would be good to have a way to navigate these easily through the astro CLI. I imagine being able to go back in time and see the output from any previous command that has been run, e.g.:

```
# List sessions
astro ls

# Show logs for session
astro output [session id] [--modules <module,names>]
```
